# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nVennR <- function(desc, byCol = 0L) {
    invisible(.Call(`_nVennR_nVennR`, desc, byCol))
}

getVennSetNames <- function() {
    .Call(`_nVennR_getVennSetNames`)
}

getVennRegion <- function(n) {
    .Call(`_nVennR_getVennRegion`, n)
}

getVennSvg <- function() {
    .Call(`_nVennR_getVennSvg`)
}

