# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Creates nVenn plot
#'
#' @param desc Description of sets, either as a list of lists or as text.
#' @param v2 verbose If true, shows messages as the nVenn plot is created.
#' @return nVenn object. As a side effect, shows the nVenn plot.
nVennDiagram <- function(desc, verbose = TRUE, byCol = 0L) {
    .Call(`_nVennR_nVennDiagram`, desc, verbose, byCol)
}

getVennSetNames <- function(nvObject) {
    .Call(`_nVennR_getVennSetNames`, nvObject)
}

getVennRegion <- function(nvObject, n) {
    .Call(`_nVennR_getVennRegion`, nvObject, n)
}

getVennSvg <- function(nvObject) {
    .Call(`_nVennR_getVennSvg`, nvObject)
}

rotateVenn <- function(nvObject, angle) {
    .Call(`_nVennR_rotateVenn`, nvObject, angle)
}

