// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nVennR
SEXP nVennR(SEXP desc, bool verbose, unsigned int byCol);
RcppExport SEXP _nVennR_nVennR(SEXP descSEXP, SEXP verboseSEXP, SEXP byColSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type desc(descSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type byCol(byColSEXP);
    rcpp_result_gen = Rcpp::wrap(nVennR(desc, verbose, byCol));
    return rcpp_result_gen;
END_RCPP
}
// getVennSetNames
List getVennSetNames(List nvObject);
RcppExport SEXP _nVennR_getVennSetNames(SEXP nvObjectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nvObject(nvObjectSEXP);
    rcpp_result_gen = Rcpp::wrap(getVennSetNames(nvObject));
    return rcpp_result_gen;
END_RCPP
}
// getVennRegion
List getVennRegion(List nvObject, SEXP n);
RcppExport SEXP _nVennR_getVennRegion(SEXP nvObjectSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nvObject(nvObjectSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(getVennRegion(nvObject, n));
    return rcpp_result_gen;
END_RCPP
}
// getVennSvg
String getVennSvg(List nvObject);
RcppExport SEXP _nVennR_getVennSvg(SEXP nvObjectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nvObject(nvObjectSEXP);
    rcpp_result_gen = Rcpp::wrap(getVennSvg(nvObject));
    return rcpp_result_gen;
END_RCPP
}
// rotateVenn
SEXP rotateVenn(List nvObject, float angle);
RcppExport SEXP _nVennR_rotateVenn(SEXP nvObjectSEXP, SEXP angleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nvObject(nvObjectSEXP);
    Rcpp::traits::input_parameter< float >::type angle(angleSEXP);
    rcpp_result_gen = Rcpp::wrap(rotateVenn(nvObject, angle));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nVennR_nVennR", (DL_FUNC) &_nVennR_nVennR, 3},
    {"_nVennR_getVennSetNames", (DL_FUNC) &_nVennR_getVennSetNames, 1},
    {"_nVennR_getVennRegion", (DL_FUNC) &_nVennR_getVennRegion, 2},
    {"_nVennR_getVennSvg", (DL_FUNC) &_nVennR_getVennSvg, 1},
    {"_nVennR_rotateVenn", (DL_FUNC) &_nVennR_rotateVenn, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nVennR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
