# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nvSimulate <- function(verbose) {
    invisible(.Call(`_nVennR_nvSimulate`, verbose))
}

nvGetRegion <- function(n) {
    .Call(`_nVennR_nvGetRegion`, n)
}

nvSvg <- function() {
    .Call(`_nVennR_nvSvg`)
}

