// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nvSimulate
void nvSimulate(bool verbose);
RcppExport SEXP _nVennR_nvSimulate(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    nvSimulate(verbose);
    return R_NilValue;
END_RCPP
}
// nvGetRegion
List nvGetRegion(unsigned int n);
RcppExport SEXP _nVennR_nvGetRegion(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nvGetRegion(n));
    return rcpp_result_gen;
END_RCPP
}
// nvSvg
String nvSvg();
RcppExport SEXP _nVennR_nvSvg() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nvSvg());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nVennR_nvSimulate", (DL_FUNC) &_nVennR_nvSimulate, 1},
    {"_nVennR_nvGetRegion", (DL_FUNC) &_nVennR_nvGetRegion, 1},
    {"_nVennR_nvSvg", (DL_FUNC) &_nVennR_nvSvg, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_nVennR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
