var annotated_dup =
[
    [ "binMap", "classbin_map.html", "classbin_map" ],
    [ "blData", "structbl_data.html", "structbl_data" ],
    [ "blst", "structblst.html", "structblst" ],
    [ "borderLine", "classborder_line.html", "classborder_line" ],
    [ "ccwangle", "classccwangle.html", "classccwangle" ],
    [ "csts", "structcsts.html", "structcsts" ],
    [ "decider", "classdecider.html", "classdecider" ],
    [ "fileText", "classfile_text.html", "classfile_text" ],
    [ "glGraphics", "classgl_graphics.html", "classgl_graphics" ],
    [ "groupIterator", "classgroup_iterator.html", "classgroup_iterator" ],
    [ "lCounter", "classl_counter.html", "classl_counter" ],
    [ "nvenn", "classnvenn.html", "classnvenn" ],
    [ "nvset", "structnvset.html", "structnvset" ],
    [ "optimizationStep", "classoptimization_step.html", "classoptimization_step" ],
    [ "outc", "structoutc.html", "structoutc" ],
    [ "outsiderInfo", "structoutsider_info.html", "structoutsider_info" ],
    [ "palettes", "classpalettes.html", "classpalettes" ],
    [ "point", "classpoint.html", "classpoint" ],
    [ "rgb", "structrgb.html", "structrgb" ],
    [ "rgn", "structrgn.html", "structrgn" ],
    [ "scale", "classscale.html", "classscale" ],
    [ "scene", "classscene.html", "classscene" ],
    [ "splitString", "classsplit_string.html", "classsplit_string" ],
    [ "springLink", "structspring_link.html", "structspring_link" ],
    [ "svgOpts", "structsvg_opts.html", "structsvg_opts" ],
    [ "tangent", "classtangent.html", "classtangent" ],
    [ "timeMaster", "classtime_master.html", "classtime_master" ]
];